alter session set "_ORACLE_SCRIPT" = true;
CREATE USER Sara IDENTIFIED BY MyPassword;
GRANT CONNECT TO Sara;
GRANT CONNECT, RESOURCE, DBA TO Sara;
GRANT CREATE SESSION TO Sara;
GRANT UNLIMITED TABLESPACE TO Sara;

GRANT
  SELECT,
  INSERT,
  UPDATE,
  DELETE
ON
EMPLOYEE
TO
sara;



